---
serverless:
  port: 7001

db:
  username: dev
  password: anByU=9c77?cD26k
  host: 0.0.0.0
  port: 3306
  logging: false
  database: openrecord
  synchronize: false

log:
  level: silly
  depth: 10
  console:
    enabled: true